apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: jerney
  namespace: argocd
spec:
  project: default

  source:
    repoURL: https://github.com/Sandip-Dutta-8/Jerney
    targetRevision: main
    path: k8s/                    # folder where jerney.yaml lives

  destination:
    server: https://kubernetes.default.svc
    namespace: jerney

  syncPolicy:
    automated:
      prune: true                 # delete resources removed from git
      selfHeal: true              # revert manual changes in cluster
    syncOptions:
      - CreateNamespace=true      # auto-create jerney namespace